
class GenerationError(Exception):
    pass

class RetryError(Exception):
    pass